'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CuteCharmIDGen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2019/1/24 #2.
        '''</summary>
        Friend ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFE.
        '''</summary>
        Friend ReadOnly Property A() As String
            Get
                Return ResourceManager.GetString("A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFD.
        '''</summary>
        Friend ReadOnly Property B() As String
            Get
                Return ResourceManager.GetString("B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FF7F.
        '''</summary>
        Friend ReadOnly Property Down() As String
            Get
                Return ResourceManager.GetString("Down", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FDFF.
        '''</summary>
        Friend ReadOnly Property L() As String
            Get
                Return ResourceManager.GetString("L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFEF.
        '''</summary>
        Friend ReadOnly Property Left() As String
            Get
                Return ResourceManager.GetString("Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdbs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdbs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FEFF.
        '''</summary>
        Friend ReadOnly Property R() As String
            Get
                Return ResourceManager.GetString("R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFDF.
        '''</summary>
        Friend ReadOnly Property Right() As String
            Get
                Return ResourceManager.GetString("Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFB.
        '''</summary>
        Friend ReadOnly Property SEL() As String
            Get
                Return ResourceManager.GetString("SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFF7.
        '''</summary>
        Friend ReadOnly Property Start() As String
            Get
                Return ResourceManager.GetString("Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFBF.
        '''</summary>
        Friend ReadOnly Property Up() As String
            Get
                Return ResourceManager.GetString("Up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FBFF.
        '''</summary>
        Friend ReadOnly Property X() As String
            Get
                Return ResourceManager.GetString("X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F7FF.
        '''</summary>
        Friend ReadOnly Property Y() As String
            Get
                Return ResourceManager.GetString("Y", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
