'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CuteCharmIDGen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2019/5/25.
        '''</summary>
        Friend ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFE.
        '''</summary>
        Friend ReadOnly Property A() As String
            Get
                Return ResourceManager.GetString("A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFD.
        '''</summary>
        Friend ReadOnly Property B() As String
            Get
                Return ResourceManager.GetString("B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttoninner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttoninner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FF7F.
        '''</summary>
        Friend ReadOnly Property Down() As String
            Get
                Return ResourceManager.GetString("Down", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dpadinner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpadinner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5E400116 C9190000
        '''96781F5F 56244BDD
        '''946332BA EAB78E29
        '''8F2BE16F 889C7227
        '''98D37471 984CD7EF
        '''04162507 79907B4A
        '''B522C464 D61FDEB7
        '''676A6325 4B9C46B2
        '''7CBBE136 E2DA7AEA
        '''28A687A3 C4ED48BA
        '''ED640B91 EB43A108
        '''AE85AF77 AE6530BC
        '''07D44AD7 47C72AE4
        '''9B2B7C07 79E1FF5F
        '''8B424CE5 6A2CC2C2
        '''CF11FCEB 7F98E365
        '''E5FBCA92 9300B00B.
        '''</summary>
        Friend ReadOnly Property FemaleLead() As String
            Get
                Return ResourceManager.GetString("FemaleLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FDFF.
        '''</summary>
        Friend ReadOnly Property L() As String
            Get
                Return ResourceManager.GetString("L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFEF.
        '''</summary>
        Friend ReadOnly Property Left() As String
            Get
                Return ResourceManager.GetString("Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F7D437DE C9170000
        '''11B29CCB 72394AD8
        '''ECAB5B77 4AFB47BE
        '''B0F3C17B F835BC77
        '''86D659B0 D96380EB
        '''2B895E2A 3BCE2DC0
        '''CE3C91D0 3CEFF2C9
        '''D0D70518 9A4433AC
        '''DFE60349 CC7E9517
        '''1494B27E BE0CC71B
        '''1C062BA4 43D79AF9
        '''9415FD2D 5078C54A
        '''C2E9785C 7AA68E3B
        '''8ABF4327 D62DF1B7
        '''9966D01A 5FDA88B8
        '''77F70AD7 8375078A
        '''0A36272A A700337E.
        '''</summary>
        Friend ReadOnly Property MaleLead() As String
            Get
                Return ResourceManager.GetString("MaleLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ovalbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ovalbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ovalbuttoninner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ovalbuttoninner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdbs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdbs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FEFF.
        '''</summary>
        Friend ReadOnly Property R() As String
            Get
                Return ResourceManager.GetString("R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFDF.
        '''</summary>
        Friend ReadOnly Property Right() As String
            Get
                Return ResourceManager.GetString("Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFB.
        '''</summary>
        Friend ReadOnly Property SEL() As String
            Get
                Return ResourceManager.GetString("SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shoulder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoulder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shoulderinner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoulderinner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFF7.
        '''</summary>
        Friend ReadOnly Property Start() As String
            Get
                Return ResourceManager.GetString("Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFBF.
        '''</summary>
        Friend ReadOnly Property Up() As String
            Get
                Return ResourceManager.GetString("Up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FBFF.
        '''</summary>
        Friend ReadOnly Property X() As String
            Get
                Return ResourceManager.GetString("X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F7FF.
        '''</summary>
        Friend ReadOnly Property Y() As String
            Get
                Return ResourceManager.GetString("Y", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
