'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CuteCharmIDGen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2019/5/25.
        '''</summary>
        Friend ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFE.
        '''</summary>
        Friend ReadOnly Property A() As String
            Get
                Return ResourceManager.GetString("A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFD.
        '''</summary>
        Friend ReadOnly Property B() As String
            Get
                Return ResourceManager.GetString("B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buttoninner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buttoninner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FF7F.
        '''</summary>
        Friend ReadOnly Property Down() As String
            Get
                Return ResourceManager.GetString("Down", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dpad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dpadinner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpadinner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 5E400116 D8D90000
        '''177F13EA AC5B8801
        '''62CD5EEC CD3106FA
        '''8DFC83DD AED33C0D
        '''3D252382 03501856
        '''5A13553D CFAB1754
        '''04F3C3E0 369BCAF3
        '''2E32084E E27C11DC
        '''89837A1F F89DC126
        '''93105F17 0A73E41E
        '''3A4F1470 C10A2246
        '''6320978A 10E8B2E2
        '''3E6E8AE3 AF06DA25
        '''91584343 028D8D68
        '''B008EB1F DCFA12C1
        '''AFA0A42C 07BE025C
        '''16C35A1E 197683FB.
        '''</summary>
        Friend ReadOnly Property FemaleLead() As String
            Get
                Return ResourceManager.GetString("FemaleLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FDFF.
        '''</summary>
        Friend ReadOnly Property L() As String
            Get
                Return ResourceManager.GetString("L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFEF.
        '''</summary>
        Friend ReadOnly Property Left() As String
            Get
                Return ResourceManager.GetString("Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F7D437DE D8D70000
        '''92B28F16 48688F7C
        '''BB1487A9 2D753F65
        '''AFC363E8 1E6C865D
        '''2B2808C1 4467C152
        '''829D8DC0 91EAC9CA
        '''1E0EB16D 9D6ADF06
        '''979FAA42 3123FED6
        '''ECAE9C32 E231DB53
        '''7F3A8BEA 05EA60BE
        '''D12C34C5 6E1E1FAF
        '''2A75E5A3 D5FE4920
        '''F983B849 E1E43D7C
        '''8068067C 63717F80
        '''72316CEF ED27D8BF
        '''5661B21E 1B9AF294
        '''3AFDB6A7 2D75076E.
        '''</summary>
        Friend ReadOnly Property MaleLead() As String
            Get
                Return ResourceManager.GetString("MaleLead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ovalbutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ovalbutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ovalbuttoninner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ovalbuttoninner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdbs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdbs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FEFF.
        '''</summary>
        Friend ReadOnly Property R() As String
            Get
                Return ResourceManager.GetString("R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFDF.
        '''</summary>
        Friend ReadOnly Property Right() As String
            Get
                Return ResourceManager.GetString("Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFFB.
        '''</summary>
        Friend ReadOnly Property SEL() As String
            Get
                Return ResourceManager.GetString("SEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shoulder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoulder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shoulderinner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shoulderinner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFF7.
        '''</summary>
        Friend ReadOnly Property Start() As String
            Get
                Return ResourceManager.GetString("Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FFBF.
        '''</summary>
        Friend ReadOnly Property Up() As String
            Get
                Return ResourceManager.GetString("Up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FBFF.
        '''</summary>
        Friend ReadOnly Property X() As String
            Get
                Return ResourceManager.GetString("X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F7FF.
        '''</summary>
        Friend ReadOnly Property Y() As String
            Get
                Return ResourceManager.GetString("Y", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
